### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by PrincewillIroka** [Bwca/iso-datestring-validator#20]
I keep getting this error when using the library in Typescript:

node_modules\iso-datestring-validator\dist\index.js:1
export*from"./is-valid-date/is-valid-date.function";export*from"./is-valid-iso-datestring/is-valid-iso-datestring.function";export*fro
m"./is-valid-time/is-valid-time.function";export*from"./is-valid-year-month/is-valid-year-month.function";
^^^^^^

SyntaxError: Unexpected token 'export'

**Comment by Bwca** [comment]
Is it node project or a frontend project with a bundler? I need more info to reproduce and look into it.

**Comment by PrincewillIroka** [comment]
I'm using it in a backend NodeJS (Typescript) project and I'm using Babel.

**Comment by Bwca** [comment]
Got it, will investigate, thanks. Most likely it's because version 2.1.3 uses ES6 modules. 
You could switch to version 2.1.2 until I fix the issue, it's commonjs so there shouldn't be any problems. The only difference between 2.1.2 and 2.1.3 being ES6 and bugfix for [datestring without time](https://github.com/Bwca/iso-datestring-validator/issues/18).

**Comment by Bwca** [comment]
I went back to commonjs module in recent version 2.1.4, you should be cool now.
